service: sso
frameworkVersion: '4.6.4'

package:
  individually: true

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs20.x
  deploymentMethod: direct
  architecture: arm64
  environment:
    COGNITO_CLIENT_ID: !Ref PrideCodeUserPoolClient

custom:
  esbuild:
  bundle: true
  minify: true
  sourcemap: false
  target: node20
  exclude:
    - '@aws-sdk/*'
  define:
    require.resolve: undefined
  platform: node
  concurrency: 10

resources:
  Resources:
    PrideCodeUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        DeletionProtection: INACTIVE
        UserPoolName: PrideCodeUserPool
        MfaConfiguration: OFF
        AutoVerifiedAttributes:
          - email
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        UsernameAttributes:
          - email
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        Policies:
          PasswordPolicy:
            MinimumLength: 10
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
            TemporaryPasswordValidityDays: 2
        Schema:
          - Name: given_name
            Mutable: true
            Required: true
            AttributeDataType: String
          - Name: family_name
            Mutable: true
            Required: true
            AttributeDataType: String
    PrideCodeUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: PrideCodeUserPoolClient
        UserPoolId: !Ref PrideCodeUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        TokenValidityUnits:
          AccessToken: hours
          RefreshToken: hours
        AccessTokenValidity: 3
        RefreshTokenValidity: 1440 # 60 dias
functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - httpApi:
          method: GET
          path: /hello
